Batch Request for owners of domains
unstoppabledomains/resolution-swift pull request #15
Opened 2020-10-13 15:07 UTC by rommex

2020-10-13 16:18 UTC, merenkoff requested changes
Some naming errors and other comments

2020-10-13 16:18 UTC, merenkoff commented on README.md
> + resolution.batchOwners(domains: ["brad.crypto", "otherbrad.crypto"]) { result in
maybe better name is owners instead of batchOwners

2020-10-13 16:18 UTC, merenkoff commented on README.md
> + resolution.batchOwners(domains: ["brad.crypto", "otherbrad.crypto"]) { result in
```suggestion
 resolution.owners(domains: ["brad.crypto", "otherbrad.crypto"]) { result in
```

2020-10-13 16:18 UTC, merenkoff commented on README.md
> +    case inconsistenDomainArray
strange error

2020-10-13 16:18 UTC, merenkoff commented on Sources/UnstoppableDomainsResolution/APIRequest.swift
> +            let strin = String(data: httpBody, encoding: .utf8)
strange name of variable

2020-10-13 16:18 UTC, merenkoff commented on Sources/UnstoppableDomainsResolution/APIRequest.swift
> +//    }
please don't provide a commented code for production

2020-10-13 16:18 UTC, merenkoff commented on Sources/UnstoppableDomainsResolution/Helpers/Types.swift
> +public typealias StringsArratResultConsumer = (Result<[String?], ResolutionError>) -> Void
```suggestion
public typealias StringsArrayResultConsumer = (Result<[String?], ResolutionError>) -> Void
```

2020-10-13 16:18 UTC, merenkoff commented on Sources/UnstoppableDomainsResolution/Resolution.swift
> +    private func catchError(_ error: Error, completion:@escaping StringsArratResultConsumer ) {
```suggestion
    private func catchError(_ error: Error, completion:@escaping StringsArrayResultConsumer ) {
```

2020-10-13 16:18 UTC, merenkoff commented on Sources/UnstoppableDomainsResolution/Resolution.swift
> +    public func batchOwners(domains: [String], completion: @escaping StringsArratResultConsumer ) {
```suggestion
    public func batchOwners(domains: [String], completion: @escaping StringsArrayResultConsumer ) {
```

2020-10-15 07:55 UTC, rommex commented on README.md
> +    case inconsistenDomainArray
This is when domains submitted in one array are supported by different NS, while they should be consistently by one NS

2020-10-15 08:01 UTC, rommex commented on README.md
> + resolution.batchOwners(domains: ["brad.crypto", "otherbrad.crypto"]) { result in
Just 'owners' doesn't reflect the idea of the batch request. It could have been just a sequence of requests...

2020-10-15 08:08 UTC, rommex commented on README.md
> + resolution.batchOwners(domains: ["brad.crypto", "otherbrad.crypto"]) { result in
Just `owners` may mean a sequence of requests. I wanted to stress that this method uses one batch request

2020-10-15 11:57 UTC, merenkoff approved these changes

2020-10-15 13:46 UTC, rommex commented on Sources/UnstoppableDomainsResolution/Resolution.swift
> +    /// - Parameter completion: A callback that resolves `Result`  with an array of `owner address`'s or `Error`
Currently the resulting array of owners is ordered and aligned with the array of domains. One-to-one consistency

2020-10-15 13:48 UTC, merged