UnregisteredDomain instead of UnspecifiedResolver
unstoppabledomains/resolution-swift pull request #36
Opened 2021-04-05 08:58 UTC by JohnnyJumper

Found a little mixup with the error code the library has been spitting out when was doing the gnosis integration. When I query anything from a domain that is not registered, I expect to get unregisteredDomain instead of UnspecifiedResolver error. 

Even though the chances of having ownership of a domain with no resolvers set are extremely low. The only domain like that I could found was paulalcock.zil. 

I guess this is considered to be a breaking change. Would love to hear some opinions regarding this.

2021-04-05 10:08 UTC, merenkoff approved these changes

2021-04-05 17:57 UTC, DeRain requested changes

2021-04-06 10:57 UTC, merenkoff commented on Sources/UnstoppableDomainsResolution/NamingServices/CNS.swift
> +                guard Utillities.isNotEmpty(owners[0]) else {
In some cases iOS code guard is more readable and logic little bit other instead of ``` if {} else {}``` construction. But in this case, I don't prefer any specific.

2021-04-06 10:57 UTC, merenkoff commented on Sources/UnstoppableDomainsResolution/NamingServices/CNS.swift
> +                guard Utillities.isNotEmpty(owners[0]) else {
> @JohnnyJumper Do we have the same errors logic for .zil? And for ENS?

For `ZNS` and `ENS`, we don't have a universal proxy reader that is used here.

2021-04-06 12:06 UTC, JohnnyJumper commented on Sources/UnstoppableDomainsResolution/NamingServices/CNS.swift
> +                guard Utillities.isNotEmpty(resolvers[0]),
I don't really have any domains that have owner addresses, but not resolver one set under .crypto tld. I do know a .zil domain with this setup: paulalcock.zil.

2021-04-07 11:45 UTC, DeRain commented on Sources/UnstoppableDomainsResolution/NamingServices/CNS.swift
> +                guard Utillities.isNotEmpty(resolvers[0]),
> I need to know at least one domain in .crypto that has no resolver but got an owner. I know such one exists on zilliqa: " paulalcock.zil ", however, it doesn't help in this case

twistedmusic.crypto

You can use website database to find domains for any use-case

2021-04-07 11:45 UTC, DeRain commented on Sources/UnstoppableDomainsResolution/NamingServices/CNS.swift
> +                guard Utillities.isNotEmpty(resolvers[0]),
cc @JohnnyJumper

2021-04-07 11:49 UTC, rommex commented on Sources/UnstoppableDomainsResolution/NamingServices/CNS.swift
> +                guard Utillities.isNotEmpty(resolvers[0]),
Any domain that has been transferred to another wallet but has not been records-managed yet. Correct @merenkoff  ?

2021-04-07 13:30 UTC, merenkoff commented on Sources/UnstoppableDomainsResolution/NamingServices/CNS.swift
> +                guard Utillities.isNotEmpty(resolvers[0]),
> Any domain that has been transferred to another wallet but has not been records-managed yet. Correct @merenkoff ?

Yes after transferring we don't have a resolver in .Crypto domains

2021-04-16 21:48 UTC, DeRain approved these changes

2021-04-19 09:04 UTC, merged