remove crypto validation except .zil
unstoppabledomains/resolution-swift pull request #42
Opened 2021-06-15 07:38 UTC by JohnnyJumper

2021-06-15 11:58 UTC, DeRain commented
@JohnnyJumper Please be sure that you are creating PR's based on UNS branch, not on master

2021-06-15 12:02 UTC, DeRain requested changes

2021-06-15 12:02 UTC, DeRain commented on Sources/UnstoppableDomainsResolution/NamingServices/CNS.swift
> +        return !domain.hasSuffix(".zil")
Do we need to keep Self.specificDomain constant?

2021-06-15 17:02 UTC, JohnnyJumper commented on Sources/UnstoppableDomainsResolution/NamingServices/CNS.swift
> +        return !domain.hasSuffix(".zil")
not really, I will remove it

2021-06-16 15:18 UTC, DeRain approved these changes

2021-06-18 13:01 UTC, merenkoff approved these changes
LGMT. Good work

2021-06-18 13:02 UTC, merged