Added ERC721 metadata methods
unstoppabledomains/resolution-swift pull request #43
Opened 2021-06-16 17:28 UTC by DancingAxolotl

2021-06-17 14:59 UTC, rommex approved these changes

2021-06-17 14:59 UTC, rommex commented on Sources/UnstoppableDomainsResolution/Helpers/TokenUriMetadata.swift
> +    let externalURL: String
`externalUrl`

2021-06-18 07:32 UTC, DeRain requested changes

2021-06-18 07:32 UTC, DeRain commented on Sources/UnstoppableDomainsResolution/Helpers/TokenUriMetadata.swift
> +struct TokenUriMetadataValue: Codable {
Let's add a few simple tests for this helper

2021-06-18 13:00 UTC, merenkoff approved these changes
LGTM if @DeRain  will approve it we will merge it to master

2021-06-18 13:01 UTC, merenkoff commented
@DeRain  Tests are added. So please review it again.

2021-06-21 07:26 UTC, DeRain commented
> LGTM if @DeRain will approve it we will merge it to master

This branch is going to be merged into `uns` branch, not in master. We are keeping all uns updates in separate branch since this introduces a big amount of changes and we want to keep master clean while we are working on uns integration.

2021-06-21 07:28 UTC, DeRain approved these changes
👍

2021-06-22 10:21 UTC, merged