Add ability to import owned tokens to resolution-swift library
unstoppabledomains/resolution-swift pull request #44
Opened 2021-06-22 10:33 UTC by JohnnyJumper

Introduce Resolution#tokensOwnedBy(address: String, service: String) throws -> [String]

Cns#tokensOwnedBy fetches the registry contract for logs on the provided address, fetches NewURI to decrypt the domains
Zns is not supported at the moment.
https://www.pivotaltracker.com/story/show/178446775

2021-06-22 10:58 UTC, merenkoff approved these changes
LGTM

2021-06-22 12:01 UTC, bogdan commented
@rommex please take a look also

2021-06-22 12:46 UTC, rommex requested changes

2021-06-22 12:46 UTC, rommex commented on Sources/UnstoppableDomainsResolution/NamingServices/CNS.swift
> +            fromBlock: "0x8A958B",
Let's extract this value as a constant.
Also let's keep in mind that for testnet - Rinkeby - this value is lower: `0x7232BC`

2021-06-22 12:46 UTC, rommex commented on Sources/UnstoppableDomainsResolution/NamingServices/CNS.swift
> +                fromBlock: "0x8A958b",
+

2021-06-22 12:46 UTC, rommex commented on Sources/UnstoppableDomainsResolution/NamingServices/CNS.swift
> +            signatureHash: "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
I suggest we extract this Transfer Event hash as  a public accessible constant

2021-06-22 12:46 UTC, rommex commented on Sources/UnstoppableDomainsResolution/NamingServices/CNS.swift
> +                signatureHash: "0xc5beef08f693b11c316c0c8394a377a0033c9cf701b8cd8afd79cecef60c3952",
As well for the NewURI hash

2021-06-23 01:14 UTC, JohnnyJumper commented
By default we are using this key for swift library: 3c25f57353234b1b853e9861050f4817
We need to whitelist the eth_getLogs method on infura for this key. Otherwise, the default settings will not work for users.

2021-06-23 03:32 UTC, rommex approved these changes
Cool

2021-06-23 06:37 UTC, DeRain commented
> By default we are using this key for swift library: 3c25f57353234b1b853e9861050f4817
> We need to whitelist the eth_getLogs method on infura for this key. Otherwise, the default settings will not work for users.

Done, thank you! 👍

2021-06-23 06:42 UTC, DeRain approved these changes
👍

2021-06-23 14:35 UTC, merged