Johnny/enable uns
unstoppabledomains/resolution-swift pull request #45
Opened 2021-06-29 23:11 UTC by JohnnyJumper

Pivotal story:
https://www.pivotaltracker.com/story/show/178483249

Rename CNS to UNS class
Migrate to the new network config https://github.com/unstoppabledomains/uns/blob/main/uns-config.json
Added a build phase script to pull the network configs and supported-keys from respective locations
use DefaultNetworkingLayer instead of metadaApiRequest

2021-06-30 09:50 UTC, rommex requested changes

2021-06-30 09:50 UTC, rommex commented on README.md
>    - `.crypto`
Should we add the new TLDs here?

2021-06-30 09:50 UTC, rommex commented on README.md
> +* `uns` resolves `.crypto` domains,
Again, UNS is not limited to `.crypto` domains as CNS is

2021-06-30 09:50 UTC, rommex commented on Sources/UnstoppableDomainsResolution/NamingServices/UNS.swift
> +              let registry = contractsContainer[ContractType.unsRegistry.name]?.address,
Don't we need to parse both CNSRegistry and UNSRegistry addresses? IE to implement `tokensOwnedBy(address: String) throws` we need CNS if the domain is 'legacy', and UNS otherwise.

2021-06-30 09:50 UTC, rommex commented on Tests/ResolutionTests/ResolutionTests.swift
> -        let cnsNetwork = try resolution.getNetwork(from: "cns");
Could be purer to extract all these literals "CNS", "zns", etc. into publicly accessible constants.

Also it is not obvious when CAPS and when lowercase. Maybe unify them? (In the future this confusion may be asking for troubles :) )

2021-06-30 14:03 UTC, merenkoff commented on Sources/UnstoppableDomainsResolution/Resolution.swift
> -        let networking = MetadataAPIRequest()
Why do not use our abstract class of Networking Layer. The idea was to provide control to developer for every request via any possible transport layer. In your case in this method, we use always our own HTTP layer.

2021-06-30 14:03 UTC, merenkoff commented on Sources/UnstoppableDomainsResolution/Resources/CNS/cnsResolver.json
> -[{
I think we need both files cnsRegistry and unsRegistry. only in case where ABI in UNS include all methods from CNS

2021-07-01 01:48 UTC, JohnnyJumper commented on Sources/UnstoppableDomainsResolution/Resolution.swift
> -        let networking = MetadataAPIRequest()
We have the possibility to set 2 different networking layers for ZNS and UNS respectfully. I guess I will use the UNS one

2021-07-01 09:12 UTC, JohnnyJumper commented on Sources/UnstoppableDomainsResolution/NamingServices/UNS.swift
> +              let registry = contractsContainer[ContractType.unsRegistry.name]?.address,
I have a slight problem with tokensOwnedBy. As an input, I am getting only the owner addresses. I don't know if there is any way to tell from what contract I should be reading. How can I know if the domain is legacy or uns?

2021-07-01 09:27 UTC, rommex commented on Sources/UnstoppableDomainsResolution/NamingServices/UNS.swift
> +              let registry = contractsContainer[ContractType.unsRegistry.name]?.address,
Yes, good point. There is a new method `registryOf()` that can be used to determine the domain's origin.

https://rinkeby.etherscan.io/address/0x299974AeD8911bcbd2C61262605b89F591a53E83#readContract

2021-07-01 16:01 UTC, DeRain requested changes

2021-07-01 16:01 UTC, DeRain commented on Tests/ResolutionTests/ResolutionTests.swift
> +            uns: NamingServiceConfig(providerUrl: "https://rinkeby.infura.io/v3/3c25f57353234b1b853e9861050f4817")
- Please, migrate all tests to testnet.
- Add tests for new TLD's

2021-07-01 17:06 UTC, JohnnyJumper commented on Sources/UnstoppableDomainsResolution/NamingServices/UNS.swift
> +              let registry = contractsContainer[ContractType.unsRegistry.name]?.address,
registryOf takes the namehash of a domain to return the correct registry address, not the owner address. It will needed to be implement but this I think is a separate PR

2021-07-02 05:46 UTC, JohnnyJumper commented on Sources/UnstoppableDomainsResolution/APIRequest.swift
> +    public func makeHttpGetRequest(url: URL, completion: @escaping TokenUriMetadataResultConsumer ) {
This is being covered under testTokenUriMetadata test

2021-07-02 11:13 UTC, rommex commented on Sources/UnstoppableDomainsResolution/NamingServices/UNS.swift
> +              let registry = contractsContainer[ContractType.unsRegistry.name]?.address,
You are right, my bad. To implement `tokensOwnedBy` we need to search (asynchronously) both CNS and UNS and then concatenate the results.
In other words, we cannot know how many domains the owner owns, nor from which registries each one of them comes from. So exhaustive search will do.

2021-07-02 14:03 UTC, DeRain commented on Sources/UnstoppableDomainsResolution/NamingServices/UNS.swift
> +        let cnsPossibleDomains = try self.parseContractForNewUri(
@rommex ARe this two calls asynchronous?

2021-07-02 14:16 UTC, DeRain requested changes

2021-07-02 14:16 UTC, DeRain commented on Tests/ResolutionTests/ResolutionTests.swift
> +    static let TEST_DOMAIN3: String = "brad.crypto"
@JohnnyJumper Could you add at least few domains with new TLD's?

I worth adding a test case which will check `isSupportedDomain` method across all new and old TLD's (and unknown TLD's as well)

2021-07-02 14:16 UTC, DeRain commented on Tests/ResolutionTests/ResolutionTests.swift
> +        assert(customRecord == "custom.vlaue")
```suggestion
        assert(customRecord == "custom.value")
```

2021-07-02 14:18 UTC, rommex commented on Sources/UnstoppableDomainsResolution/NamingServices/UNS.swift
> +        let cnsPossibleDomains = try self.parseContractForNewUri(
Seems synchronous to me 😶

2021-07-02 15:46 UTC, DeRain commented on Sources/UnstoppableDomainsResolution/NamingServices/UNS.swift
> +        let cnsPossibleDomains = try self.parseContractForNewUri(
@JohnnyJumper Could you make two async requests then?

2021-07-02 17:03 UTC, JohnnyJumper commented on Sources/UnstoppableDomainsResolution/NamingServices/UNS.swift
> +        let cnsPossibleDomains = try self.parseContractForNewUri(
They are synchronous

2021-07-07 09:38 UTC, JohnnyJumper commented on Sources/UnstoppableDomainsResolution/NamingServices/UNS.swift
> +        }
Is this the correct way to ensure those functions will be called asynchronously? 
@rommex

2021-07-07 15:18 UTC, rommex commented on Sources/UnstoppableDomainsResolution/NamingServices/UNS.swift
> +        }
Very close with 2 updates:
1. Each call `self. self.parseContractForNewUri(...)` must be wrapped in `DispatchQueue.global().async { }` since you want them to execute synchronously.
2. To catch the finished execution of both methods you use `group.notify(queue: .global()) { <code when both finished>}` instead of `.wait()`

2021-07-08 11:34 UTC, DeRain commented on Sources/UnstoppableDomainsResolution/NamingServices/UNS.swift
> +        asyncGroup.wait()
Looks good, @merenkoff  or @rommex please confirm that this is a proper way to handle async operations in swift. Thank you!

2021-07-08 11:42 UTC, DeRain approved these changes
Looks good!

2021-07-08 18:18 UTC, rommex approved these changes

2021-07-09 01:41 UTC, merged