Use newuri for unhash
unstoppabledomains/resolution-swift pull request #47
Opened 2021-07-01 15:32 UTC by DancingAxolotl

2021-07-01 17:06 UTC, DeRain requested changes

2021-07-01 17:06 UTC, DeRain commented on Sources/UnstoppableDomainsResolution/NamingServices/CNS.swift
> +            let registryContract = try self.buildContract(address: self.contracts.registryAddress, type: .registry)
Let's pull registry address from ProxyReader contract

2021-07-01 17:06 UTC, DeRain commented on Sources/UnstoppableDomainsResolution/ABI/ABICoder.swift
> +    public func decodeEventTopics(eventName: String, eventLogTopics: [Data], eventLogData: Data) throws -> [String: Any] {
Please add simple tests for abicoder

2021-07-02 11:00 UTC, rommex commented on Sources/UnstoppableDomainsResolution/APIRequest.swift
> +        let dataTask = URLSession.shared.dataTask(with: urlRequest) { data, response, _ in
Can we use the `networkingLayer` here instead?
It's a good general idea to provide the client an option to implement networking themselves if they want.

2021-07-02 11:32 UTC, JohnnyJumper commented on Sources/UnstoppableDomainsResolution/APIRequest.swift
> +        let dataTask = URLSession.shared.dataTask(with: urlRequest) { data, response, _ in
Somehow I got the same commit in uns branch without the implementation of  MetadataApiRequest. I have moved it on networking layer and used uns one. Even though it is possible to use different networking layers on uns and zns.in #45

2021-07-02 11:32 UTC, JohnnyJumper commented on Sources/UnstoppableDomainsResolution/NamingServices/CNS.swift
> +            let registryContract = try self.buildContract(address: self.contracts.registryAddress, type: .registry)
I believe this is the same as tokenOwnedBy [from master](https://github.com/unstoppabledomains/resolution-swift/pull/44)

2021-07-13 14:05 UTC, DancingAxolotl commented on Sources/UnstoppableDomainsResolution/APIRequest.swift
> +        let dataTask = URLSession.shared.dataTask(with: urlRequest) { data, response, _ in
Thanks, I've merged it with changes in #45 
I wasn't aware that we provide an option for custom networking.

2021-07-13 14:06 UTC, merged