feat: zil support on polygon
unstoppabledomains/resolution-swift pull request #70
Opened 2022-06-09 22:35 UTC by enaqx

2022-06-14 18:52 UTC, rommex approved these changes
LGTM with minor comments

2022-06-14 18:52 UTC, rommex commented on README.md
> +Library support three networks at the moment Ethereum, Polygon and Zilliqa. You can update each network separately.
typo: must be `supports`

2022-06-14 18:52 UTC, rommex commented on Sources/UnstoppableDomainsResolution/NamingServices/UNS.swift
> +//        for (domain, (l2owner, l1owner)) in zip(domains, zip(l2Result, l1Result)) {
Dead code?

2022-06-14 18:52 UTC, rommex commented on Sources/UnstoppableDomainsResolution/Resolution.swift
> +//        DispatchQueue.global(qos: .utility).async { [weak self] in
Dead code?

2022-06-14 18:52 UTC, rommex commented on Sources/UnstoppableDomainsResolution/Resolution.swift
> +//        if domain.hasSuffix(".zil") {
Dead code?

2022-06-15 13:13 UTC, DancingAxolotl requested changes
Good work! 
I left some comments for ZNS functions that should be addressed, but otherwise the PR looks good.

2022-06-15 13:13 UTC, DancingAxolotl commented on Sources/UnstoppableDomainsResolution/NamingServices/UNS.swift
> +                         {try self.zlayer.locations(domains: domains)}]
ZNS locations method throws a "methodNotSupported" error. We should either handle the error or return something for ZNS locations. We can probably check domain owner and return a partial `Location` struct

2022-06-23 01:58 UTC, enaqx commented
Updated, please take a look

2022-06-23 21:49 UTC, merged